package com.example.demo.dao;

import com.example.demo.domain.RolePermissionRelation;
import com.example.demo.domain.RolePermissionRelationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RolePermissionRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RolePermissionRelation
     *
     * @mbg.generated
     */
    long countByExample(RolePermissionRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RolePermissionRelation
     *
     * @mbg.generated
     */
    int deleteByExample(RolePermissionRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RolePermissionRelation
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer rppid);

    void deleteByRoleId(Integer roleid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RolePermissionRelation
     *
     * @mbg.generated
     */
    int insert(RolePermissionRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RolePermissionRelation
     *
     * @mbg.generated
     */
    int insertSelective(RolePermissionRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RolePermissionRelation
     *
     * @mbg.generated
     */
    List<RolePermissionRelation> selectByExample(RolePermissionRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RolePermissionRelation
     *
     * @mbg.generated
     */
    RolePermissionRelation selectByPrimaryKey(Integer rppid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RolePermissionRelation
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") RolePermissionRelation record, @Param("example") RolePermissionRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RolePermissionRelation
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") RolePermissionRelation record, @Param("example") RolePermissionRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RolePermissionRelation
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RolePermissionRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RolePermissionRelation
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RolePermissionRelation record);
}