package com.example.demo.dao;

import com.example.demo.domain.UserRoleRelation;
import com.example.demo.domain.UserRoleRelationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserRoleRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserRoleRelation
     *
     * @mbg.generated
     */
    long countByExample(UserRoleRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserRoleRelation
     *
     * @mbg.generated
     */
    int deleteByExample(UserRoleRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserRoleRelation
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer urrid);

    void deleteByUserId(int userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserRoleRelation
     *
     * @mbg.generated
     */
    int insert(UserRoleRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserRoleRelation
     *
     * @mbg.generated
     */
    int insertSelective(UserRoleRelation record);

    void insertUserId(int userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserRoleRelation
     *
     * @mbg.generated
     */
    List<UserRoleRelation> selectByExample(UserRoleRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserRoleRelation
     *
     * @mbg.generated
     */
    UserRoleRelation selectByPrimaryKey(Integer urrid);

    UserRoleRelation selectByUserId(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserRoleRelation
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") UserRoleRelation record, @Param("example") UserRoleRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserRoleRelation
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") UserRoleRelation record, @Param("example") UserRoleRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserRoleRelation
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserRoleRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserRoleRelation
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserRoleRelation record);

    void updateByUserId(@Param("UserId") int uid,@Param("RoleId")int rid);
}