package com.example.demo.dao;

import com.example.demo.domain.UserPermissionRelation;
import com.example.demo.domain.UserPermissionRelationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserPermissionRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserPermissionRelation
     *
     * @mbg.generated
     */
    long countByExample(UserPermissionRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserPermissionRelation
     *
     * @mbg.generated
     */
    int deleteByExample(UserPermissionRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserPermissionRelation
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer uprid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserPermissionRelation
     *
     * @mbg.generated
     */
    int insert(UserPermissionRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserPermissionRelation
     *
     * @mbg.generated
     */
    int insertSelective(UserPermissionRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserPermissionRelation
     *
     * @mbg.generated
     */
    List<UserPermissionRelation> selectByExample(UserPermissionRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserPermissionRelation
     *
     * @mbg.generated
     */
    UserPermissionRelation selectByPrimaryKey(Integer uprid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserPermissionRelation
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") UserPermissionRelation record, @Param("example") UserPermissionRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserPermissionRelation
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") UserPermissionRelation record, @Param("example") UserPermissionRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserPermissionRelation
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserPermissionRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table UserPermissionRelation
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserPermissionRelation record);
}